version: "3"

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/x86_64
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "social_media"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
