version: '3'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/x86_64
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - cse479
    environment:
      TZ: Asia/Dhaka
      MYSQL_DATABASE: 'social_media'
      MYSQL_ALLOW_EMPTY_PASSWORD: true

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/.env:/.env
    ports:
      - 8000:8000
    networks:
      - cse479
    depends_on:
      - mysql

networks:
  cse479:
    driver: bridge
